version: "3.9"

services:
  agixt:
    container_name: agixt-dev
    build: .
    restart: unless-stopped
    ports:
      - "7437:7437"
    env_file:
      - .env
    networks:
      - dev-stack_dev-network

networks:
  dev-stack_dev-network:
    external: true
